FROM rust:1.89-bookworm AS chef
WORKDIR /app
COPY Cargo.toml Cargo.lock ./
COPY bibavpn ./bibavpn
RUN cargo build --release -p bibavpn --bin bibavpn-client

FROM debian:bookworm-slim
RUN apt-get update \
    && apt-get install -y --no-install-recommends ca-certificates \
    && rm -rf /var/lib/apt/lists/*
COPY --from=chef /app/target/release/bibavpn-client /usr/local/bin/bibavpn-client
EXPOSE 1080 18080
ENTRYPOINT ["/usr/local/bin/bibavpn-client"]
